print(3+4)
print(3-4)
print(3*4)
print(3%4)
print(3/4)
print(3**4)
print(3//4)
print("Kevin Yu")
print("Yu")
print("USA")
print("I am enjoying 30 days of python")
print(type(10))
print(type(9.8))
print(type(3.14))
print(type(4-4j))
print(type(['Asabeneh','Python', 'Finland']))
print(type("Yu"))
print(type("Kevin"))
print(type("USA"))